# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go get -u github.com/jteeuwen/go-bindata/...
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - 
    main: ./main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -a -installsuffix cgo -s -w -X github.com/dohr-michael/storyline-api/cmd.Version={{.ProjectName}} -X github.com/dohr-michael/storyline-api/cmd.Revision={{.ShortCommit}} -X github.com/dohr-michael/storyline-api/cmd.Time={{.Date}}
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
dockers:
  -
    image_templates:
    - "jdrbahamut/storyline-api:lastest"
    - "jdrbahamut/storyline-api:{{.Tag}}"
    - "jdrbahamut/storyline-api:{{.Major}}"
    # Template of the docker build flags.
    # Name templates of the built binaries that should be used.
    binaries:
    - storyline-api
    # Template of the docker build flags.
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
    extra_files:
    #- config.yml
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: dohr-michael
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/dohr-michael/storyline-api
  description: Golang project starter
  test: |
    system "#{bin}/storyline-api version"
scoop:
  bucket:
    owner: dohr-michael
    name: scoop-bucket
  homepage: https://github.com/dohr-michael/storyline-api
  description: Golang project starter
  license: MIT
