# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GO111MODULE: 'on' # Enable go module
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  CGO_ENABLED: '0'

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    go mod download
  workingDirectory: '$(modulePath)'
  displayName: 'go download dependencies'

- script: |
    go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'

- script: |
    go build -v -a -installsuffix cgo -s -w -X github.com/$(build.repository.name)/cmd.Version=$(Build.BuildNumber) -X github.com/$(build.repository.name)/cmd.Revision=$(Build.SourceVersion) -X github.com/$(build.repository.name)/cmd.Time=$(date +%Y-%m-%dT%H:%M:%S%z) ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Build'


