# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GO111MODULE: 'on' # Enable go module
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
  GORELEASER_PATH: '$(System.ArtifactsDirectory)'
steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    mkdir -p '$(modulePath)/dist'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'
- task: DownloadGitHubRelease@0
  inputs:
    connection: github-download
    userRepository: goreleaser/goreleaser
    itemPattern: goreleaser_Linux_x86_64.tar.gz
    downloadPath: ${GORELEASER_PATH}
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: ${GORELEASER_PATH}/goreleaser_Linux_x86_64.tar.gz
    destinationFolder: ${GORELEASER_PATH}
    cleanDestinationFolder: false
- script: |
    ${GORELEASER_PATH}/./goreleaser --rm-dist --snapshot
    ls -lsa
    ls -lsa dist
  workingDirectory: '$(modulePath)'
  displayName: 'Deps, test and build'

